#spring.application.name=wallet-service
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/json_wallet
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#server.port=8080
#
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#

spring.application.name=wallet-service

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.jigykwyfxgvddpiwpjti
spring.datasource.password=JastipAdpro2026!
spring.datasource.driver-class-name=org.postgresql.Driver